# Generated by Django 6.0.5 on 2026-09-01 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('transactions', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_otps', to='customers.account'),
        ),
    ]
